
-- ----------------------------
-- Table structure for vcos_country
-- ----------------------------
DROP TABLE IF EXISTS `vcos_country`;
CREATE TABLE `vcos_country` (
  `country_id` int(11) NOT NULL AUTO_INCREMENT,
  `country_code` varchar(32) DEFAULT NULL,
  `country_number` varchar(32) DEFAULT NULL COMMENT '数字代号',
  `country_name` varchar(128) DEFAULT NULL,
  `country_name_en` varchar(128) DEFAULT NULL,
  `country_short_code` char(3) DEFAULT NULL COMMENT '3 Character',
  `country_state` int(1) DEFAULT '0' COMMENT '状态 0可用',
  `mark` varchar(128) DEFAULT NULL,
  `create_by` varchar(32) DEFAULT NULL,
  `create_time` int(11) DEFAULT '0',
  PRIMARY KEY (`country_id`),
  KEY `country_code` (`country_short_code`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=496 DEFAULT CHARSET=utf8 COMMENT='国家表';

-- ----------------------------
-- Records of vcos_country
-- ----------------------------
INSERT INTO `vcos_country` VALUES ('1', 'KY', '411', '开曼群岛', 'Cayman Islands', 'CYM', '0', '', 'admin', '1406029497');
INSERT INTO `vcos_country` VALUES ('3', 'KZ', '145', '哈萨克斯坦', 'Kazakhstan', 'KAZ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('5', 'LA', '119', '老挝', 'Lao People\'s Democratic Republic', 'LAO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('7', 'LB', '120', '黎巴嫩', 'Lebanon', 'LBN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('9', 'LC', '437', '圣卢西亚', 'Saint Lucia', 'LCA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('11', 'LI', '323', '列支敦士登', 'Liechtenstein', 'LIE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('13', 'LK', '134', '斯里兰卡', 'Sri Lanka', 'LKA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('15', 'LR', '225', '利比里亚', 'Liberia', 'LBR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('17', 'AD', '314', '安道尔', 'Andorra', 'AND', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('19', 'AE', null, '阿拉伯联合酋长国', 'United Arab Emirates', 'ARE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('21', 'AF', '101', '阿富汗', 'Afghanistan', 'AFG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('23', 'AG', '401', '安提瓜和巴布达', 'Antigua and Barbuda', 'ATG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('25', 'AI', null, '安圭拉岛', 'Anguilla', 'AIA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('27', 'AL', '313', '阿尔巴尼亚', 'Albania', 'ALB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('29', 'OM', '126', '阿曼', 'Oman', 'OMN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('31', 'PA', '432', '巴拿马', 'Panama', 'PAN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('33', 'PE', '434', '秘鲁', 'Peru', 'PER', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('35', 'PF', '623', '法属波利尼西亚', 'French Polynesia', 'PYF', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('37', 'PG', '611', '巴布亚新几内亚', 'Papua New Guinea', 'PNG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('39', 'PH', '129', '菲律宾', 'Philippines', 'PHL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('41', 'PK', '127', '巴基斯坦', 'Pakistan', 'PAK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('43', 'BF', '251', '布基纳法索', 'Burkina Faso', 'BFA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('45', 'BG', '316', '保加利亚', 'Bulgaria', 'BGR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('47', 'BH', '102', '巴林', 'Bahrain', 'BHR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('49', 'BI', '205', '布隆迪', 'Burundi', 'BDI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('51', 'BJ', '203', '贝宁', 'Benin', 'BEN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('53', 'BM', null, '百慕大群岛', 'Bermuda', 'BMU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('55', 'TZ', '247', '坦桑尼亚', 'Tanzania, United Republic of', 'TZA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('57', 'JO', '117', '约旦', 'Jordan', 'JOR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('59', 'KE', '224', '肯尼亚', 'Kenya', 'KEN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('61', 'KH', '107', '柬埔寨', 'Cambodia', 'KHM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('63', 'GF', '420', '法属圭亚那', 'French Guiana', 'GUF', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('65', 'GH', '220', '加纳', 'Ghana', 'GHA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('67', 'GI', '320', '直布罗陀', 'Gibraltar', 'GIB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('69', 'GL', '503', '格陵兰', 'Greenland', 'GRL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('71', 'GM', '219', '冈比亚', 'Gambia', 'GMB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('73', 'ID', '112', '印度尼西亚', 'Indonesia', 'IDN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('75', 'IE', '306', '爱尔兰', 'Ireland', 'IRL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('77', 'IL', '115', '以色列', 'Israel', 'ISR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('79', 'IM', null, '马恩岛', 'Isle of Man', 'IMY', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('81', 'BN', '105', '文莱', 'Brunei Darussalam', 'BRN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('83', 'BO', '408', '玻利维亚', 'Bolivia', 'BOL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('85', 'LT', '336', '立陶宛', 'Lithuania', 'LTU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('87', 'MK', null, '马其顿,前南斯拉夫共和国', 'Macedonia, The Former Yugoslav Republic of', 'MKD', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('89', 'ML', '229', '马里', 'Mali', 'MLI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('91', 'MM', '106', '缅甸', 'Myanmar', 'MMR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('93', 'MN', '124', '蒙古', 'Mongolia', 'MNG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('95', 'UA', '347', '乌克兰', 'Ukraine', 'UKR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('97', 'UG', '250', '乌干达', 'Uganda', 'UGA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('99', 'US', '502', '美国', 'United States', 'USA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('101', 'KW', '118', '科威特', 'Kuwait', 'KWT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('103', 'LU', '308', '卢森堡', 'Luxembourg', 'LUX', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('105', 'LV', '335', '拉脱维亚', 'Latvia', 'LVA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('107', 'LY', '226', '利比亚', 'Libyan Arab Jamahiriya', 'LBY', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('109', 'UY', '444', '乌拉圭', 'Uruguay', 'URY', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('111', 'UZ', '149', '乌兹别克斯坦', 'Uzbekistan', 'UZB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('113', 'VA', null, '梵蒂冈城', 'Holy See (Vatican City State)', 'VAT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('115', 'VC', '439', '圣文森特和格林纳丁斯', 'Saint Vincent and the Grenadines', 'VCT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('117', 'VE', '445', '委内瑞拉', 'Venezuela', 'VEN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('119', 'VG', null, '维尔京群岛（英属）', 'Virgin Islands, British', 'VGB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('121', 'VI', null, '维尔京群岛', 'Virgin Islands, U.S.', 'VIR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('123', 'VN', '141', '越南', 'Viet Nam', 'VNM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('125', 'VU', '608', '瓦努阿图', 'Vanuatu', 'VUT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('127', 'WF', null, '瓦利斯群岛和富图纳群岛', 'Wallis and Futuna', 'WLF', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('129', 'GP', null, '瓜德罗普岛', 'Guadeloupe', 'GLP', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('131', 'GQ', '216', '赤道几内亚', 'Equatorial Guinea', 'GNQ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('133', 'GR', '310', '希腊', 'Greece', 'GRC', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('135', 'GS', null, '南乔治亚和南桑德威奇群岛', 'South Georgia and the South Sandwich Islands', 'SGS', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('137', 'GT', '423', '危地马拉', 'Guatemala', 'GTM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('139', 'GU', null, '关岛', 'Guam', 'GUM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('141', 'IT', '307', '意大利', 'Italy', 'ITA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('143', 'DM', null, '多米尼加', 'Dominica', 'DMA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('145', 'DO', '418', '多米尼加共和国', 'Dominican Republic', 'DOM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('147', 'CH', '331', '瑞士', 'Switzerland', 'CHE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('149', 'MA', '232', '摩洛哥', 'Morocco', 'MAR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('151', 'KM', '212', '科摩罗', 'Comoros', 'COM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('153', 'KN', null, '圣基茨和尼维斯', 'Saint Kitts and Nevis', 'KNA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('155', 'KP', '109', '朝鲜', 'Korea, Democratic People\'s Republic of', 'PRK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('157', 'KR', '133', '韩国', 'Korea, Republic of', 'KOR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('159', 'MP', null, '北马里亚纳群岛', 'Northern Mariana Islands', 'MNP', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('161', 'MR', '230', '毛里塔尼亚', 'Mauritania', 'MRT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('163', 'MS', '430', '蒙特塞拉特', 'Montserrat', 'MSR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('165', 'MU', '231', '毛里求斯', 'Mauritius', 'MUS', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('167', 'MW', '228', '马拉维', 'Malawi', 'MWI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('169', 'MY', '122', '马来西亚', 'Malaysia', 'MYS', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('171', 'NA', '234', '纳米比亚', 'Namibia', 'NAM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('173', 'NC', '607', '新喀里多尼亚', 'New Caledonia', 'NCL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('175', 'DZ', '201', '阿尔及利亚', 'Algeria', 'DZA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('177', 'EC', '419', '厄瓜多尔', 'Ecuador', 'ECU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('179', 'EE', '334', '爱沙尼亚', 'Estonia', 'EST', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('181', 'EG', '215', '埃及', 'Egypt', 'EGY', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('183', 'EH', '245', '西撒哈拉 ', 'Western Sahara', 'ESH', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('185', 'ER', '258', '厄立特里亚', 'Eritrea', 'ERI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('187', 'ES', '312', '西班牙', 'Spain', 'ESP', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('189', 'ET', '217', '埃塞俄比亚', 'Ethiopia', 'ETH', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('191', 'FI', '318', '芬兰', 'Finland', 'FIN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('193', 'FJ', null, '斐济群岛', 'Fiji', 'FJI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('195', 'FK', null, '福克兰群岛(马尔维纳斯群岛)', 'Falkland Islands (Malvinas)', 'FLK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('197', 'FM', null, '密克罗尼西亚', 'Micronesia, Federated States of', 'FSM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('199', 'FO', '357', '法罗群岛', 'Faroe Islands', 'FRO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('201', 'FX', null, '法属城市', 'France, Metropolitan', 'FXX', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('203', 'GB', '303', '英国', 'United Kingdom', 'GBR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('205', 'GD', '421', '格林纳达', 'Grenada', 'GRD', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('207', 'CI', '223', '科特迪瓦', 'Cote D\'Ivoire', 'CIV', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('209', 'CK', '602', '库克群岛', 'Cook Islands', 'COK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('211', 'CL', '412', '智利', 'Chile', 'CHL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('213', 'CM', '206', '喀麦隆', 'Cameroon', 'CMR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('215', 'CN', '142', '中国', 'China', 'CHN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('217', 'NU', null, '纽埃', 'Niue', 'NIU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('219', 'GW', null, '几内亚比绍', 'Guinea-Bissau', 'GNB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('221', 'GY', '424', '圭亚那', 'Guyana', 'GUY', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('223', 'HK', '110', '中国香港', 'Hong Kong', 'HKG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('225', 'HM', null, '赫德和麦克唐纳群岛', 'Heard Isl & McDonald Isl', 'HMD', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('227', 'HN', '426', '洪都拉斯', 'Honduras', 'HND', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('229', 'HR', '351', '克罗地亚', 'Croatia', 'HRV', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('231', 'HT', '425', '海地', 'Haiti', 'HTI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('233', 'HU', '321', '匈牙利', 'Hungary', 'HUN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('235', 'CO', '413', '哥伦比亚', 'Colombia', 'COL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('237', 'CS', '349', '塞尔维亚和黑山 ', 'Serbia and Montenegro', 'CIL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('239', 'CU', '416', '古巴', 'Cuba', 'CUB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('241', 'CX', null, '圣诞岛', 'Christmas Island', 'CXR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('243', 'CZ', '352', '捷克共和国', 'Czech Republic', 'CZE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('245', 'DE', '304', '德国', 'Germany', 'DEU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('247', 'DK', '302', '丹麦', 'Denmark', 'DNK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('249', 'BS', '404', '巴哈马', 'Bahamas', 'BHS', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('251', 'BV', null, '布韦岛', 'Bouvet Isl', 'BVT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('253', 'BY', '340', '白俄罗斯', 'Belarus', 'BLR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('255', 'BZ', '406', '伯利兹', 'Belize', 'BLZ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('257', 'CC', null, '科科斯群岛（基灵群岛）', 'Cocos (Keeling) Islands', 'CCK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('259', 'CD', null, '刚果民主共和国', 'Congo, The Democratic Republic of the', 'COD', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('261', 'CG', '213', '刚果', 'Congo', 'COG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('263', 'RE', null, '留尼汪岛', 'Réunion', 'REU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('265', 'RO', '328', '罗马尼亚', 'Romania', 'ROM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('267', 'RU', null, '俄罗斯', 'Russian Federation', 'RUS', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('269', 'RW', '238', '卢旺达', 'Rwanda', 'RWA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('271', 'SA', '131', '沙特阿拉伯', 'Saudi Arabia', 'SAU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('273', 'SB', '613', '所罗门群岛', 'Solomon Islands', 'SLB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('275', 'PT', '311', '葡萄牙', 'Portugal', 'PRT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('277', 'PW', null, '帕劳群岛', 'Palau', 'PLW', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('279', 'PY', '433', '巴拉圭', 'Paraguay', 'PRY', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('281', 'QA', '130', '卡塔尔', 'Qatar', 'QAT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('283', 'IS', '322', '冰岛', 'Iceland', 'ISL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('285', 'LS', '255', '莱索托', 'Lesotho', 'LSO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('287', 'GN', '221', '几内亚', 'Guinea', 'GIN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('289', 'MC', '325', '摩纳哥', 'Monaco', 'MCO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('291', 'MD', '343', '摩尔多瓦', 'Moldova, Republic of', 'MDA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('293', 'MG', '227', '马达加斯加', 'Madagascar', 'MDG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('295', 'MH', '621', '马绍尔群岛', 'Marshall Islands', 'MHL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('297', 'YE', null, '也门', 'Yemen', 'YEM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('299', 'WS', '617', '萨摩亚', 'Samoa', 'WSM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('301', 'YT', '259', '马约特岛', 'Mayotte', 'MYT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('303', 'YU', null, '塞尔维亚和门第内哥罗', 'Yugoslavia', 'YUG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('305', 'ZA', '244', '南非', 'South Africa', 'ZAF', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('307', 'ZM', '253', '赞比亚', 'Zambia', 'ZMB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('309', 'ZW', '254', '津巴布韦', 'Zimbabwe', 'ZWE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('311', 'TF', null, '法属南极地区', 'French Southern Territories', 'ATF', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('313', 'TG', '248', '多哥', 'Togo', 'TGO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('315', 'TH', '136', '泰国', 'Thailand', 'THA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('317', 'TJ', '147', '塔吉克斯坦', 'Tajikistan', 'TJK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('319', 'TK', null, '托克劳', 'Tokelau', 'TKL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('321', 'TM', '148', '土库曼斯坦', 'Turkmenistan', 'TKM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('323', 'TN', '249', '突尼斯', 'Tunisia', 'TUN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('325', 'TO', '614', '汤加', 'Tonga', 'TON', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('327', 'TP', '144', '东帝汶', 'East Timor', 'TMP', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('329', 'TR', '137', '土耳其', 'Turkey', 'TUR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('331', 'TT', '442', '特立尼达和多巴哥', 'Trinidad and Tobago', 'TTO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('333', 'TV', '619', '图瓦卢', 'Tuvalu', 'TUV', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('335', 'PL', '327', '波兰', 'Poland', 'POL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('337', 'PM', null, '圣皮埃尔岛和密克隆岛', 'Saint Pierre and Miquelon', 'SPM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('339', 'PN', null, '皮特克恩群岛', 'Pitcairn', 'PCN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('341', 'PR', '435', '波多黎各', 'Puerto Rico', 'PRI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('343', 'PS', null, '巴勒斯坦当局', 'Palestinian Territory, Occupied', 'PSE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('345', 'BE', '301', '比利时', 'Belgium', 'BEL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('347', 'AM', '338', '亚美尼亚', 'Armenia', 'ARM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('349', 'AN', null, '荷属安的列斯群岛', 'Netherlands Antilles', 'ANT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('351', 'AO', '202', '安哥拉', 'Angola', 'AGO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('353', 'AR', '402', '阿根廷', 'Argentina', 'ARG', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('355', 'AT', '315', '奥地利', 'Austria', 'AUT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('357', 'AU', '601', '澳大利亚', 'Australia', 'AUS', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('359', 'AZ', '339', '阿塞拜疆', 'Azerbaijan', 'AZE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('361', 'BB', '405', '巴巴多斯', 'Barbados', 'BRB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('363', 'BD', '103', '孟加拉国', 'Bangladesh', 'BGD', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('365', 'SY', '135', '叙利亚', 'Syrian Arab Republic', 'SYR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('367', 'SZ', '257', '斯威士兰', 'Swaziland', 'SWZ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('369', 'TC', null, '特克斯群岛和凯科斯群岛', 'Turks and Caicos Islands', 'TCA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('371', 'TD', '211', '乍得', 'Chad', 'TCD', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('373', 'SK', '353', '斯洛伐克', 'Slovakia (Slovak Republic)', 'SVK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('375', 'SL', '242', '塞拉利昂', 'Sierra Leone', 'SLE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('377', 'SM', '329', '圣马力诺', 'San Marino', 'SMR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('379', 'SN', '240', '塞内加尔', 'Senegal', 'SEN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('381', 'SO', '243', '索马里', 'Somalia', 'SOM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('383', 'SR', '441', '苏里南', 'Suriname', 'SUR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('385', 'ST', '239', '圣多美和普林西比', 'Sao Tome and Principe', 'STP', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('387', 'SV', '440', '萨尔瓦多', 'El Salvador', 'SLV', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('389', 'IN', '111', '印度', 'India', 'IND', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('391', 'IO', null, '不列颠印度洋属土', 'British Indian Ocean Territory', 'IOT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('393', 'IQ', '114', '伊拉克', 'Iraq', 'IRQ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('395', 'IR', '113', '伊朗', 'Iran, Islamic Republic Of', 'IRN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('397', 'NF', '610', '诺福克岛', 'Norfolk Island', 'NFK', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('399', 'NG', '236', '尼日利亚', 'Nigeria', 'NGA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('401', 'NI', '431', '尼加拉瓜', 'Nicaragua', 'NIC', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('403', 'NL', '309', '荷兰', 'Netherlands', 'NLD', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('405', 'NO', '326', '挪威', 'Norway', 'NOR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('407', 'NP', '125', '尼泊尔', 'Nepal', 'NPL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('409', 'NR', '606', '瑙鲁', 'Nauru', 'NRU', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('411', 'SJ', null, '斯瓦尔巴群岛和扬马延', 'Svalbard and Jan Mayen', 'SJM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('413', 'SC', '241', '塞舌尔', 'Seychelles', 'SYC', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('415', 'SD', '246', '苏丹', 'Sudan', 'SDN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('417', 'SE', '330', '瑞典', 'Sweden', 'SWE', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('419', 'SG', '132', '新加坡', 'Singapore', 'SGP', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('421', 'SH', null, '圣赫勒拿岛', 'Saint Helena', 'SHN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('423', 'SI', '350', '斯洛文尼亚', 'Slovenia', 'SVN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('425', 'NE', '235', '尼日尔', 'Niger', 'NER', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('427', 'CR', '415', '哥斯达黎加', 'Costa Rica', 'CRI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('429', 'CV', '208', '佛得角', 'Cape Verde', 'CPV', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('431', 'CY', '108', '塞浦路斯', 'Cyprus', 'CYP', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('433', 'DJ', '214', '吉布提', 'Djibouti', 'DJI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('435', 'BR', '410', '巴西', 'Brazil', 'BRA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('437', 'BT', '104', '不丹', 'Bhutan', 'BTN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('439', 'BW', null, '博茨瓦纳', 'Botswana', 'BWA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('441', 'CA', '501', '加拿大', 'Canada', 'CAN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('443', 'CF', '209', '中非共和国', 'Central African Republic', 'CAF', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('445', 'AQ', null, '南极洲', 'Antarctica', 'ATA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('447', 'AS', null, '美属萨摩亚', 'American samoa', 'ASM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('449', 'AW', null, '阿鲁巴', 'Aruba', 'ABW', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('451', 'BA', null, '波斯尼亚和黑塞哥维那', 'Bosnia And Herzegovina', 'BIH', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('453', 'TW', null, '中国台湾', 'Taiwan/ROC', 'TWN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('455', 'FR', '305', '法国', 'France', 'FRA', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('457', 'GA', '218', '加蓬', 'Gabon', 'GAB', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('459', 'GE', null, '乔治亚', 'Georgia', 'GEO', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('461', 'JM', '427', '牙买加', 'Jamaica', 'JAM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('463', 'JP', '116', '日本', 'Japan', 'JPN', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('465', 'KG', '146', '吉尔吉斯斯坦', 'Kyrgyzstan', 'KGZ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('467', 'KI', '618', '基里巴斯', 'Kiribati', 'KIR', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('469', 'UM', null, '美属小奥特兰群岛', 'United States Minor Outlying Islands', 'UMI', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('471', 'MO', '121', '中国澳门', 'Macau', 'MAC', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('473', 'MQ', null, '马提尼克岛', 'Martinique', 'MTQ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('475', 'MT', '324', '马耳他', 'Malta', 'MLT', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('477', 'MV', '123', '马尔代夫', 'Maldives', 'MDV', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('479', 'MX', '429', '墨西哥', 'Mexico', 'MEX', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('481', 'MZ', '233', '莫桑比克', 'Mozambique', 'MOZ', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('483', 'NZ', '609', '新西兰', 'New Zealand', 'NZL', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('485', 'BL', null, '圣巴瑟米', 'Saint Barthelemy', 'BLM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('487', 'MF', null, '法属圣马丁', 'Saint Martin (French Part)', 'MAF', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('489', 'BQ', '409', '博内尔', 'Bonaire', 'BES', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('491', 'CW', '417', '库腊索岛', 'Curacao', 'CUW', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('493', 'SX', null, '荷属圣马丁', 'Sint Maarten', 'SXM', '0', null, null, '0');
INSERT INTO `vcos_country` VALUES ('495', 'cq', null, '华夏', 'China', 'cha', '0', '', 'admin', '1438333716');
